sudo: required
language: java
jdk:
  - oraclejdk8
addons:
  mariadb: '10.2'
before_script:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS TripCoTestDB'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON TripCoTestDB.* TO 'travis'@'%'"
  - mysql  TripCoTestDB < CREATE TABLE airports (id int, latitude varchar(1000), longitude varchar(1000)); >

